#!/bin/sh
set -eu
export DEBUG=${DEBUG:-0}
cd /app
exec chpst -u app   \
     uwsgi_python34 \
     --master       \
     --http-socket :$PORT                \
     --processes   ${UWSGI_PROCESSES:-2} \
     --threads     ${UWSGI_THREADS:-32}  \
     --module      ${PYTHON_MODULE}      \
     --callable    ${PYTHON_CALLABLE}
