RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
            python-all-dev \
            python-pip \
            python-wheel \
            uwsgi-plugin-python \
    && rm -rf /var/cache/apt /var/lib/apt/lists
RUN pip install -U pip wheel

ENV PORT=5000
ENV PYTHON_MODULE=backend
ENV PYTHON_CALLABLE=app
