arg node_release=node_6.x
run curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key \
    | apt-key add - \
    && echo "deb https://deb.nodesource.com/$node_release jessie main" \
    > /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -qq nodejs \
    && rm -rf /var/cache/apt /var/lib/apt/lists \
    && echo "nodejs: $(nodejs --version)" \
    && echo "npm: $(npm --version)"
run npm install -g http-server
