FROM unit9/base:latest
MAINTAINER Kamil Cholewiński <kamil.cholewinski@unit9.com>

WORKDIR /app
RUN adduser --system \
    --home /app --no-create-home \
    --disabled-login --group app \
    --uid 999
