RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
            python3-all-dev \
            python3-pip \
            python3-wheel \
            uwsgi-plugin-python3 \
    && rm -rf /var/cache/apt /var/lib/apt/lists
RUN pip3 install -U pip wheel

ENV PORT=5000
ENV PYTHON_MODULE=backend
ENV PYTHON_CALLABLE=app
